/** @const {ShadowJS} */ var ArrayBuffer;
/** @const {ShadowJS} */ var Float32Array;
/** @const {ShadowJS} */ var KamiCljHost;
/** @const {ShadowJS} */ var Uint32Array;
/** @const {ShadowJS} */ var Uint8Array;
/** @const {ShadowJS} */ var fetch;
/** @const {ShadowJS} */ var module;
/** @const {ShadowJS} */ var requestAnimationFrame;
ShadowJS.prototype.NEGATIVE_INFINITY;
ShadowJS.prototype.NaN;
ShadowJS.prototype.POSITIVE_INFINITY;
ShadowJS.prototype.ceilingEntry;
ShadowJS.prototype.cleanup;
ShadowJS.prototype.floorEntry;
ShadowJS.prototype.fromCharCode;
ShadowJS.prototype.getLength;
ShadowJS.prototype.register_material;
ShadowJS.prototype.register_mesh;
ShadowJS.prototype.register_shader;
ShadowJS.prototype.stringify;
ShadowJS.prototype.submit_frame;
ShadowJS.prototype.unbounded_unshift;